# Generated by Django 3.0.2 on 2020-01-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('falta_programar_cita', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaltaPorgramarCita',
            new_name='FaltaProgramarCita',
        ),
    ]
