# Generated by Django 3.0.2 on 2020-01-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falta_programar_cita', '0002_auto_20200122_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faltaprogramarcita',
            name='dia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='faltaprogramarcita',
            name='dx',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='faltaprogramarcita',
            name='edad',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='faltaprogramarcita',
            name='estado',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='faltaprogramarcita',
            name='fecha_actualizacion',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='faltaprogramarcita',
            name='fecha_creacion',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='faltaprogramarcita',
            name='fecha_hora',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='faltaprogramarcita',
            name='lugar_residencia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='faltaprogramarcita',
            name='nombre',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='faltaprogramarcita',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='faltaprogramarcita',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='faltaprogramarcita',
            name='psiquiatra',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='faltaprogramarcita',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='faltaprogramarcita',
            name='sexo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='faltaprogramarcita',
            name='telefono',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
