# Generated by Django 3.0.2 on 2020-01-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falta_programar_cita', '0004_auto_20200123_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faltaprogramarcita',
            name='dia',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
