# Generated by Django 3.0.2 on 2020-01-28 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falta_programar_cita', '0006_auto_20200123_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faltaprogramarcita',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faltaprogramarcita',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faltaprogramarcita',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=25, null=True)),
                ('fecha', models.DateTimeField(null=True)),
                ('dia', models.CharField(max_length=50, null=True)),
                ('codigo_paisa', models.CharField(max_length=100, null=True)),
                ('hermanos', models.TextField(null=True)),
                ('persona_evalua', models.CharField(max_length=100, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(null=True)),
                ('hospitalizado', models.CharField(max_length=10, null=True)),
                ('codigo_alternativo', models.CharField(max_length=100, null=True)),
                ('procedencia', models.CharField(max_length=60, null=True)),
                ('faltan_datos_red_cap', models.CharField(max_length=10, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('id_paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='falta_programar_cita.FaltaProgramarCita')),
            ],
        ),
    ]
