# Generated by Django 3.0.2 on 2020-01-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falta_programar_cita', '0007_auto_20200127_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='codigo_alternativo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='codigo_paisa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='faltan_datos_red_cap',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hermanos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hospitalizado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='persona_evalua',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='procedencia',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
